Use better sanity check for 'abort if no commits'
2d4274c (Abort when the repository has no commits., 2018-09-26) tries to
exit gracefully with a helpful error message when it isn't possible to
use `git subtree` because the repository is in the unborn branch state.

This usually happens right after the repository initialization but it
can also happen after `git checkout --orphan=foo`. The current sanity
check detects the former but not the latter.

Use `rev-parse --verify` in order to only proceed if HEAD is resolvable,
detecting both cases.

diff --git a/aurpublish.in b/aurpublish.in
--- a/aurpublish.in
+++ b/aurpublish.in
@@ -104,8 +104,8 @@ elif [[ ! ${toplevel} -ef ${PWD} ]]; then
 fi
 
 # sanity check
-if (( $(git rev-list -n 1 --all | wc -l) == 0 )); then
-    echo "error: cannot be run from a repository without any commits"
+if ! git rev-parse -q --verify HEAD > /dev/null ; then
+    echo "error: cannot be run from a branch without any commits"
     echo "At least commit a README.md or something..."
     exit 1
 fi
