Abort when the repository has no commits.
It's natural to assume e.g. aurpublish -p pkg-to-import, but this
doesn't work, because most git commands will fail if there isn't at
least some form of HEAD ref -- including both ls-tree and subtree pull.

Fail with an explicit error message rather than logging errors from
git(1) while still trying unsuccessfully to do things.

Reported-by: Ethan Rakoff <ethan@ethanrakoff.com>

diff --git a/aurpublish.in b/aurpublish.in
--- a/aurpublish.in
+++ b/aurpublish.in
@@ -104,6 +104,11 @@ elif [[ ! ${toplevel} -ef ${PWD} ]]; then
 fi
 
 # sanity check
+if (( $(git rev-list -n 1 --all | wc -l) == 0 )); then
+    echo "error: cannot be run from a repository without any commits"
+    echo "At least commit a README.md or something..."
+    exit 1
+fi
 if (( ! ( PULL_SUBTREE || SETUP ) )) && ! is_package_in_git "${package}"; then
     echo "${0##*/}: unrecognized package '${1}'"
     echo "Try '${0##*/} --help' for more information."
